export const OFFICIAL_TEMPLATES = [
  {
    name: 'Beneficiary Management System',
    description: 'Complete NGO beneficiary tracking with deduplication, field forms, and automated reports.',
    category: 'ngo',
    icon: 'users',
    version: '1.0.0',
    isOfficial: true,
    includes: [
      { type: 'entity', name: 'beneficiary', label: 'Beneficiary Records', icon: 'user' },
      { type: 'entity', name: 'household', label: 'Household Records', icon: 'home' },
      { type: 'form', name: 'Beneficiary Registration', icon: 'form' },
      { type: 'form', name: 'Home Visit Assessment', icon: 'clipboard' },
      { type: 'workflow', name: 'Beneficiary Approval', icon: 'check-circle' },
      { type: 'dashboard', name: 'Beneficiary Overview', icon: 'dashboard' },
      { type: 'report', name: 'Monthly Beneficiary Report', icon: 'file-text' },
      { type: 'rules', name: 'Data Quality Rules', icon: 'shield' },
    ],
    installPayload: {
      entities: [
        {
          name: 'beneficiary',
          description: 'Individual beneficiary receiving aid or services',
          attributes: [
            { name: 'first_name', displayName: 'First Name', dataType: 'string', isRequired: true, isIdentifier: true },
            { name: 'last_name', displayName: 'Last Name', dataType: 'string', isRequired: true, isIdentifier: true },
            { name: 'nrc', displayName: 'NRC Number', dataType: 'string', isRequired: true, isIdentifier: true, validationRules: { regex: '^\\d{6}/\\d{2}/\\d{1}$' } },
            { name: 'phone', displayName: 'Phone Number', dataType: 'string', isRequired: false },
            { name: 'gender', displayName: 'Gender', dataType: 'string', isRequired: false },
            { name: 'date_of_birth', displayName: 'Date of Birth', dataType: 'date', isRequired: false },
            { name: 'age', displayName: 'Age', dataType: 'number', isRequired: false },
            { name: 'district', displayName: 'District', dataType: 'string', isRequired: true },
            { name: 'province', displayName: 'Province', dataType: 'string', isRequired: false },
            { name: 'village', displayName: 'Village/Area', dataType: 'string', isRequired: false },
            { name: 'marital_status', displayName: 'Marital Status', dataType: 'string', isRequired: false },
            { name: 'household_size', displayName: 'Household Size', dataType: 'number', isRequired: false },
            { name: 'income_level', displayName: 'Monthly Income (ZMW)', dataType: 'number', isRequired: false },
            { name: 'vulnerability_category', displayName: 'Vulnerability Category', dataType: 'string', isRequired: false },
            { name: 'registration_date', displayName: 'Registration Date', dataType: 'date', isRequired: true },
            { name: 'status', displayName: 'Status', dataType: 'string', isRequired: true },
            { name: 'program', displayName: 'Program Enrolled', dataType: 'string', isRequired: false },
          ],
          matchingRules: [
            {
              name: 'NRC + Name Matching',
              ruleType: 'fuzzy',
              fieldWeights: { nrc: 0.5, first_name: 0.25, last_name: 0.25 },
              threshold: 0.8,
            },
          ],
        },
        {
          name: 'household',
          description: 'Household group linked to beneficiaries',
          attributes: [
            { name: 'household_id', displayName: 'Household ID', dataType: 'string', isRequired: true, isIdentifier: true },
            { name: 'head_of_household', displayName: 'Head of Household', dataType: 'string', isRequired: true },
            { name: 'head_nrc', displayName: 'Head NRC', dataType: 'string', isRequired: true },
            { name: 'total_members', displayName: 'Total Members', dataType: 'number', isRequired: true },
            { name: 'address', displayName: 'Address', dataType: 'string', isRequired: false },
            { name: 'district', displayName: 'District', dataType: 'string', isRequired: true },
            { name: 'province', displayName: 'Province', dataType: 'string', isRequired: false },
          ],
        },
      ],
      forms: [
        {
          name: 'Beneficiary Registration',
          description: 'Register a new beneficiary',
          formSchema: {
            fields: [
              { name: 'first_name', type: 'text', required: true, label: 'First Name' },
              { name: 'last_name', type: 'text', required: true, label: 'Last Name' },
              { name: 'nrc', type: 'text', required: true, label: 'NRC Number' },
              { name: 'phone', type: 'text', required: false, label: 'Phone Number' },
              { name: 'gender', type: 'select', required: false, label: 'Gender', options: ['Male', 'Female', 'Other'] },
              { name: 'date_of_birth', type: 'date', required: false, label: 'Date of Birth' },
              { name: 'district', type: 'select', required: true, label: 'District', options: ['Lusaka', 'Kitwe', 'Ndola', 'Chipata', 'Livingstone', 'Kabwe', 'Chingola', 'Luanshya'] },
              { name: 'province', type: 'select', required: false, label: 'Province', options: ['Lusaka', 'Copperbelt', 'Eastern', 'Southern', 'Central', 'Northern', 'Western', 'Muchinga', 'Luapula', 'North-Western'] },
              { name: 'village', type: 'text', required: false, label: 'Village/Area' },
              { name: 'household_size', type: 'number', required: false, label: 'Household Size' },
              { name: 'income_level', type: 'number', required: false, label: 'Monthly Income (ZMW)' },
              { name: 'vulnerability_category', type: 'select', required: false, label: 'Vulnerability Category', options: ['Elderly', 'Child-headed', 'Disabled', 'Chronically ill', 'Single parent', 'None'] },
              { name: 'program', type: 'select', required: false, label: 'Program', options: ['Cash Transfer', 'Food Aid', 'Education Support', 'Health Support', 'Livelihood'] },
              { name: 'notes', type: 'textarea', required: false, label: 'Notes' },
            ],
          },
        },
        {
          name: 'Home Visit Assessment',
          description: 'Field assessment during home visit',
          formSchema: {
            fields: [
              { name: 'beneficiary_nrc', type: 'text', required: true, label: 'Beneficiary NRC' },
              { name: 'visit_date', type: 'date', required: true, label: 'Visit Date' },
              { name: 'housing_type', type: 'select', required: true, label: 'Housing Type', options: ['Permanent', 'Semi-permanent', 'Traditional', 'Temporary'] },
              { name: 'has_electricity', type: 'boolean', required: false, label: 'Has Electricity' },
              { name: 'has_water', type: 'boolean', required: false, label: 'Has Clean Water' },
              { name: 'food_security', type: 'select', required: true, label: 'Food Security', options: ['Secure', 'Moderately insecure', 'Severely insecure'] },
              { name: 'children_in_school', type: 'number', required: false, label: 'Children in School' },
              { name: 'health_status', type: 'select', required: false, label: 'Health Status', options: ['Good', 'Fair', 'Poor', 'Critical'] },
              { name: 'assistance_needed', type: 'textarea', required: false, label: 'Assistance Needed' },
              { name: 'recommendations', type: 'textarea', required: false, label: 'Recommendations' },
            ],
          },
        },
      ],
      workflows: [
        {
          name: 'Beneficiary Approval',
          description: 'New beneficiary registration requires supervisor approval',
          triggerType: 'event',
          triggerConfig: { entityName: 'beneficiary', event: 'record.created' },
          failureStrategy: 'stop',
          steps: [
            {
              id: 'step1',
              type: 'condition',
              name: 'High vulnerability?',
              conditions: {
                field: 'vulnerability_category',
                operator: 'in',
                value: ['Elderly', 'Child-headed', 'Disabled'],
                trueStep: 'step2_urgent',
                falseStep: 'step3_normal',
              },
            },
            {
              id: 'step2_urgent',
              type: 'notification',
              name: 'Alert Supervisor (Urgent)',
              config: { channel: 'in_app', recipient: 'admin', template: 'URGENT: New {{vulnerability_category}} beneficiary requires immediate approval. Name: {{first_name}} {{last_name}}, NRC: {{nrc}}' },
              nextStep: 'step4',
            },
            {
              id: 'step3_normal',
              type: 'notification',
              name: 'Notify Reviewer',
              config: { channel: 'in_app', recipient: 'admin', template: 'New beneficiary registration: {{first_name}} {{last_name}}, NRC: {{nrc}}, District: {{district}}' },
              nextStep: 'step4',
            },
            {
              id: 'step4',
              type: 'approval',
              name: 'Supervisor Review',
              config: { assigneeRole: 'admin', deadlineHours: 48, escalation: { action: 'auto_approve' } },
              nextStep: 'step5',
            },
            {
              id: 'step5',
              type: 'script',
              name: 'Mark as Approved',
              config: { action: 'update_record', field: 'status', value: 'approved' },
            },
          ],
        },
      ],
      dashboards: [
        {
          name: 'Beneficiary Overview',
          description: 'Key metrics for beneficiary management',
          isDefault: true,
          widgets: [
            { name: 'Total Beneficiaries', widgetType: 'kpi_card', config: { entityName: 'beneficiary', field: 'Total Beneficiaries', sparkline: true }, position: { x: 0, y: 0, w: 3, h: 2 } },
            { name: 'Active Programs', widgetType: 'kpi_card', config: { entityName: 'beneficiary', field: 'Active Programs', aggregation: 'distinct', sparkline: false }, position: { x: 3, y: 0, w: 3, h: 2 } },
            { name: 'Data Quality Score', widgetType: 'kpi_card', config: { entityName: 'beneficiary', field: 'Quality Score' }, position: { x: 6, y: 0, w: 3, h: 2 } },
            { name: 'Pending Approvals', widgetType: 'number', config: { entityName: 'beneficiary', field: 'Pending', filters: { status: 'pending' } }, position: { x: 9, y: 0, w: 3, h: 2 } },
            { name: 'By District', widgetType: 'bar_chart', config: { entityName: 'beneficiary', groupBy: 'district', limit: 10 }, position: { x: 0, y: 2, w: 6, h: 4 } },
            { name: 'By Vulnerability', widgetType: 'pie_chart', config: { entityName: 'beneficiary', groupBy: 'vulnerability_category', limit: 6 }, position: { x: 6, y: 2, w: 6, h: 4 } },
            { name: 'Recent Registrations', widgetType: 'table', config: { entityName: 'beneficiary', fields: ['first_name', 'last_name', 'district', 'program', 'status'], limit: 10 }, position: { x: 0, y: 6, w: 12, h: 4 } },
          ],
        },
      ],
      validationRules: [
        { name: 'NRC Format', targetEntity: 'beneficiary', targetField: 'nrc', ruleType: 'regex', ruleConfig: { regex: '^\\d{6}/\\d{2}/\\d{1}$' }, errorMessage: 'NRC must match format: 123456/78/1', severity: 'error' },
        { name: 'Age Range', targetEntity: 'beneficiary', targetField: 'age', ruleType: 'range', ruleConfig: { min: 0, max: 120 }, errorMessage: 'Age must be between 0 and 120', severity: 'error' },
        { name: 'Name Required', targetEntity: 'beneficiary', targetField: 'first_name', ruleType: 'required', ruleConfig: {}, errorMessage: 'First name is required', severity: 'error' },
        { name: 'District Required', targetEntity: 'beneficiary', targetField: 'district', ruleType: 'required', ruleConfig: {}, errorMessage: 'District is required', severity: 'error' },
      ],
      autoLinkRules: [
        {
          name: 'Link by NRC',
          sourceEntityType: 'beneficiary',
          targetEntityType: 'beneficiary',
          fieldMappings: [{ sourceField: 'nrc', targetField: 'nrc', matchType: 'exact' }],
          relationshipType: 'same_person',
          autoAcceptAbove: 0.95,
          suggestAbove: 0.5,
          priority: 10,
        },
        {
          name: 'Household by Address',
          sourceEntityType: 'beneficiary',
          targetEntityType: 'beneficiary',
          fieldMappings: [
            { sourceField: 'district', targetField: 'district', matchType: 'exact' },
            { sourceField: 'village', targetField: 'village', matchType: 'exact' },
          ],
          relationshipType: 'household_member',
          autoAcceptAbove: 0.9,
          suggestAbove: 0.5,
          priority: 5,
        },
      ],
    },
  },
];